image: node:10.16.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - node --version
          - npm --version
          - npm install
          - npm install -g gulp-cli
          - gulp default