name: Build
on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      # pnpm dependencies cannot be cached until pnpm is installed
      # WORKAROUND: https://github.com/actions/setup-node/issues/531
      - name: Extract cached dependencies
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Update dependencies
        run: pnpm install

      - name: build
        run: pnpm run build.debug